version: "3.9"

services:
  app:
    build: .
    container_name: arenda_app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always
